import re

with open('src/lib/i18n/dict/play.ts', 'r', encoding='utf-8') as f:
    content = f.read()

vi_dict = {
    "play.home.title1": "Chơi cờ vua trực tuyến",
    "play.home.title2": "trên bàn cờ chuyên dụng để chiến thắng.",
    "play.home.subtitle": "{n} cấp độ bot, đấu xếp hạng trực tuyến và phân tích chuyên sâu giúp bạn tiến bộ.",
    "play.home.newGame": "Ván mới",
    "play.home.playOnline": "Chơi online",
    "play.home.customSetup": "Tuỳ chỉnh",
    "play.home.passAndPlay": "Chơi 2 người",
    "play.home.stat.botLevels": "Cấp độ bot",
    "play.home.stat.personalities": "Tính cách bot",
    "play.home.stat.variants": "Biến thể",
    "play.home.feature.bots.title": "Bot & tính cách",
    "play.home.feature.bots.text": "{personalities} tính cách qua {levels} cấp độ sức mạnh, nhịp suy nghĩ như người thật.",
    "play.home.feature.puzzles.title": "Bài tập chiến thuật",
    "play.home.feature.puzzles.text": "Luyện tập từ chính sai lầm của bạn với phương pháp lặp lại ngắt quãng.",
    "play.home.feature.review.title": "Phân tích & thống kê",
    "play.home.feature.review.text": "Đánh giá từ nước hay đến sai lầm, biểu đồ ưu thế và độ chính xác từng giai đoạn.",
    "play.home.feature.online.title": "Đấu xếp hạng trực tuyến",
    "play.home.feature.online.text": "Hệ số Glicko-2, ghép cặp nhanh và đồng hồ thời gian thực chính xác.",
    "play.home.quickModes": "Chơi nhanh",
    "play.home.mode.local": "2 người",
    "play.home.mode.share": "Chia sẻ",
    "play.home.mode.analysis": "Phân tích",
    "play.home.mode.games": "Ván đấu",
    "play.home.closing.title": "Ván mới chỉ cách một cú nhấp",
    "play.home.closing.text": "Không cần tải về. Chơi được cả khi ngoại tuyến. {tagline}",
    "play.home.closing.newGame": "Ván mới",
    "play.home.closing.playOnline": "Chơi online",
    "play.hub.title": "Chơi",
    "play.hub.subtitle": "Các chế độ đều hoạt động tốt khi ngoại tuyến.",
    "play.hub.card.ai.title": "Đấu với bot",
    "play.hub.card.ai.text": "15 cấp độ, 7 tính cách, nhịp suy nghĩ như người thật.",
    "play.hub.card.local.title": "Chơi 2 người",
    "play.hub.card.local.text": "Hai người, một thiết bị, đồng hồ thi đấu thật.",
    "play.hub.card.online.title": "Đấu xếp hạng trực tuyến",
    "play.hub.card.online.text": "Ghép cặp thời gian thực với hệ số Elo.",
    "play.hub.card.share.title": "Chia sẻ qua liên kết / PGN",
    "play.hub.card.share.text": "Cờ qua thư: đồng bộ nước đi qua URL hoặc PGN.",
    "play.hub.card.variants.title": "Biến thể",
    "play.hub.card.variants.text": "Chess960, Ba lần chiếu tướng, Vua trên đồi và nhiều hơn nữa.",
    "play.hub.card.analysis.title": "Bàn phân tích",
    "play.hub.card.analysis.text": "Bàn cờ tự do với đánh giá máy theo yêu cầu.",
    "play.hub.comingSoon": "Sắp ra mắt",
    "play.hub.soon.tournaments.title": "Giải đấu",
    "play.hub.soon.tournaments.text": "Đấu trường, nhánh loại trực tiếp và bảng xếp hạng.",
    "play.hub.soon.badge": "Sắp có",
    "play.ai.title": "Đấu với máy",
    "play.ai.subtitle": "Stockfish 18 (WASM) chạy trực tiếp trên thiết bị của bạn, đảm bảo tính riêng tư.",
    "play.ai.strength": "Trình độ",
    "play.ai.levelLabel": "Cấp {level} — {title}",
    "play.ai.sliderBeginner": "Người mới",
    "play.ai.sliderMax": "Máy tối đa",
    "play.ai.personality": "Tính cách",
    "play.ai.botBadge": "BOT",
    "play.ai.yourColor": "Quân của bạn",
    "play.ai.colorWhite": "Trắng",
    "play.ai.colorBlack": "Đen",
    "play.ai.colorRandom": "Ngẫu nhiên",
    "play.ai.variant": "Biến thể",
    "play.ai.timeControl": "Thời gian",
    "play.ai.startGame": "Bắt đầu",
    "play.ai.gameStatus": "Trạng thái",
    "play.ai.finished": "Đã kết thúc",
    "play.ai.live": "Đang diễn ra",
    "play.ai.variantLabel": "Biến thể",
    "play.ai.openingLabel": "Khai cuộc",
    "play.ai.engineDepth": "Độ sâu máy",
    "play.ai.engineSetup": "Thiết lập máy",
    "play.ai.engineUnavailable": "Máy không khả dụng: {error}",
    "play.ai.you": "Bạn",
    "play.ai.playerLevel": "Cấp {level} · {title} · {strength}",
    "play.ai.notation": "Biên bản",
    "play.ai.move": "Nước {n}",
    "play.ai.resign": "Đầu hàng",
    "play.ai.draw": "Hoà",
    "play.ai.rematch": "Đấu lại",
    "play.ai.viewResult": "Xem kết quả",
    "play.ai.newSetup": "Thiết lập mới",
    "play.ai.resignConfirm": "Bạn có chắc muốn đầu hàng?",
    "play.ai.gameSaved": "Đã lưu ván đấu vào kho lưu trữ",
    "play.ai.gameSavedDesc": "Mở lại để xem từng nước đi và phân tích máy.",
    "play.ai.viewAction": "Xem",
    "play.ai.standard": "Không giới hạn",
    "play.local.title": "Chơi 2 người",
    "play.local.subtitle": "Dùng chung một thiết bị và lần lượt đi quân.",
    "play.local.variant": "Biến thể",
    "play.local.timeControl": "Thời gian",
    "play.local.autoFlip": "Tự động xoay bàn cờ",
    "play.local.startGame": "Bắt đầu",
    "play.local.black": "Đen",
    "play.local.white": "Trắng",
    "play.local.localPlayer": "Người chơi tại chỗ",
    "play.local.gameStatus": "Trạng thái",
    "play.local.finished": "Đã kết thúc",
    "play.local.live": "Đang diễn ra",
    "play.local.variantLabel": "Biến thể",
    "play.local.standard": "Cổ điển",
    "play.local.openingLabel": "Khai cuộc",
    "play.local.movesLabel": "Số nước",
    "play.local.notation": "Biên bản",
    "play.local.move": "Nước {n}",
    "play.local.resign": "Đầu hàng",
    "play.local.resignConfirm": "{color} chịu thua?",
    "play.local.draw": "Hoà",
    "play.local.flip": "Xoay bàn",
    "play.local.restart": "Chơi lại",
    "play.local.gameSaved": "Đã lưu ván đấu",
    "play.local.viewAction": "Xem",
    "play.share.metaTitle": "Chia sẻ ván đấu qua liên kết — {app}",
    "play.share.metaDescription": "Đánh cờ theo lượt: mỗi nước đi tạo ra một mã PGN và liên kết gửi cho đối thủ.",
    "play.share.ogDescription": "Cờ qua thư không cần máy chủ: đồng bộ nước đi qua PGN hoặc URL.",
    "play.share.turnToMove": "{color} đi",
    "play.share.manualSync": "Đồng bộ",
    "play.share.flipBoard": "Xoay bàn",
    "play.share.newGame": "Ván mới",
    "play.share.linkTitle": "Liên kết theo lượt",
    "play.share.linkDesc": "Đi quân, rồi gửi liên kết này. Đối thủ mở liên kết để đi nước tiếp theo.",
    "play.share.copyLink": "Sao chép liên kết",
    "play.share.copyPgn": "Sao chép PGN",
    "play.share.linkCopied": "Đã sao chép liên kết",
    "play.share.pgnCopied": "Đã sao chép PGN",
    "play.share.clipboardUnavailable": "Không thể truy cập bộ nhớ tạm",
    "play.share.loadPgnTitle": "Nạp file PGN",
    "play.share.loadPgnPlaceholder": "Dán PGN hoặc danh sách nước đi (1. e4 e5 ...)",
    "play.share.loadMoves": "Nạp nước đi",
    "play.share.noMovesFound": "Không tìm thấy nước đi nào",
    "play.share.pgnCouldNotReplay": "Không thể phát lại PGN này",
    "play.share.loadedMoves": "Đã nạp {n} nước đi",
    "play.share.white": "Trắng",
    "play.share.black": "Đen",
    "play.share.manualSyncStatus": "{color} đi · nước {ply} · đồng bộ tay",
    "play.games.title": "Ván đấu của tôi",
    "play.games.subtitleCount": "{n} ván trong kho lưu trữ.",
    "play.games.syncedNote": "Đã đồng bộ với tài khoản.",
    "play.games.localOnlyNote": "Chỉ lưu cục bộ — đăng nhập để đồng bộ.",
    "play.games.archiveNote": "Kho lưu trữ vĩnh viễn — không thể xoá ván đấu.",
    "play.games.statTotal": "Tổng số",
    "play.games.statWins": "Thắng",
    "play.games.statDraws": "Hoà",
    "play.games.statLosses": "Thua",
    "play.games.filterAll": "Tất cả",
    "play.games.filterAi": "Đấu máy",
    "play.games.filterLocal": "2 người",
    "play.games.filterOnline": "Trực tuyến",
    "play.games.loadingOnline": "Đang tải ván đấu...",
    "play.games.emptyTitle": "Chưa có ván đấu nào",
    "play.games.emptyText": "Ván đấu với máy, với bạn hoặc trực tuyến sẽ tự động xuất hiện ở đây.",
    "play.games.startPlaying": "Bắt đầu chơi",
    "play.games.opponentName": "Đối thủ {id}",
    "play.games.win": "Thắng",
    "play.games.loss": "Thua",
    "play.games.draw": "Hoà",
    "play.games.inProgress": "Đang diễn ra",
    "play.games.you": "Bạn",
    "play.games.unknownOpening": "Chưa rõ khai cuộc",
    "play.games.movesCount": "{n} nước",
    "play.games.accuracy": "Độ chính xác",
    "play.games.vsBadge": "vs",
    "play.detail.metaTitle": "Chi tiết ván đấu — {app}",
    "play.detail.metaDescription": "Xem lại ván đấu với biểu đồ đánh giá, độ chính xác và xuất PGN.",
    "play.detail.ogDescription": "Xem lại ván đấu với đánh giá máy và độ chính xác.",
    "play.detail.notFoundTitle": "Không tìm thấy ván đấu",
    "play.detail.notFoundText": "Ván đấu không còn trong kho lưu trữ cục bộ.",
    "play.detail.backToGames": "Quay lại ván đấu",
    "play.detail.myGames": "Ván đấu của tôi",
    "play.detail.firstMove": "Nước đầu",
    "play.detail.prevMove": "Nước trước",
    "play.detail.nextMove": "Nước sau",
    "play.detail.lastMove": "Nước cuối",
    "play.detail.flip": "Xoay bàn",
    "play.detail.openAnalysis": "Mở bàn phân tích",
    "play.detail.copyPgn": "PGN",
    "play.detail.pgnCopied": "Đã sao chép PGN",
    "play.detail.clipboardUnavailable": "Không thể truy cập bộ nhớ tạm",
    "play.detail.evaluation": "Đánh giá",
    "play.detail.whiteAccuracy": "Độ chính xác Trắng",
    "play.detail.blackAccuracy": "Độ chính xác Đen",
    "play.detail.deepReview": "Phân tích sâu",
    "play.detail.deepReviewDesc": "Máy tính toán kỹ hơn (~900ms/nước, 5 phương án) và gợi ý chi tiết cho mỗi sai lầm.",
    "play.detail.rerunReview": "Phân tích lại",
    "play.detail.runDeepReview": "Phân tích sâu",
    "play.detail.reviewIntro": "Phân tích để xem biểu đồ đánh giá và độ chính xác. Mọi thứ được tính toán cục bộ.",
    "play.detail.reviewing": "Đang phân tích {done}/{total}...",
    "play.detail.runReview": "Chạy phân tích",
    "play.detail.moves": "Nước đi",
    "play.detail.mode": "Chế độ",
    "play.detail.modeAi": "Đấu máy",
    "play.detail.modeLocal": "2 người",
    "play.detail.variant": "Biến thể",
    "play.detail.timeControl": "Thời gian",
    "play.detail.opening": "Khai cuộc",
    "play.detail.movesLabel": "Số nước",
    "play.detail.played": "Đã chơi",
    "play.detail.reviewComplete": "Phân tích hoàn tất",
    "play.detail.deepReviewComplete": "Phân tích sâu hoàn tất",
    "play.detail.reviewCompleteDesc": "Độ chính xác — Trắng {w}%, Đen {b}%",
    "play.detail.puzzlesAdded": "Đã thêm {n} bài tập",
    "play.detail.reviewFailed": "Phân tích thất bại",
    "play.onlineDetail.metaTitle": "Chi tiết ván trực tuyến — {app}",
    "play.onlineDetail.metaDescription": "Xem lại ván đấu xếp hạng trực tuyến cùng đánh giá máy.",
    "play.onlineDetail.ogDescription": "Xem lại ván đấu xếp hạng trực tuyến cùng đánh giá máy.",
    "play.onlineDetail.loading": "Đang tải ván đấu...",
    "play.onlineDetail.notFoundTitle": "Không tìm thấy ván đấu",
    "play.onlineDetail.win": "Thắng",
    "play.onlineDetail.loss": "Thua",
    "play.onlineDetail.draw": "Hoà",
    "play.onlineDetail.inProgress": "Đang diễn ra",
    "play.onlineDetail.modeOnline": "Xếp hạng trực tuyến",
    "play.onlineDetail.opponentName": "Đối thủ {id}",
    "play.online.title": "Chơi trực tuyến",
    "play.online.subtitle": "Ghép cặp với đối thủ cùng trình độ theo thời gian thực.",
    "play.online.matchmaking": "Ghép trận",
    "play.online.variant": "Biến thể",
    "play.online.timeControl": "Thời gian",
    "play.online.cancelSearch": "Huỷ tìm kiếm",
    "play.online.findOpponent": "Tìm đối thủ",
    "play.online.waitingText": "Đang tìm đối thủ cùng trình độ.",
    "play.online.signedInAs": "Đã đăng nhập: {email}",
    "play.online.variantStandard": "Cổ điển",
    "play.online.variantChess960": "Chess960",
    "play.online.tcBullet1": "Cực nhanh 1 phút",
    "play.online.tcBlitz3": "Chớp nhoáng 3 phút",
    "play.online.tcBlitz5": "Chớp nhoáng 5 phút",
    "play.online.tcRapid10": "Nhanh 10 phút",
    "play.online.tcRapid15": "Nhanh 15+10",
    "play.online.tcClassical30": "Cổ điển 30 phút",
    "play.settings.metaTitle": "Cài đặt — {app}",
    "play.settings.metaDescription": "Tuỳ chỉnh bàn cờ, bộ quân, âm thanh và hiệu năng máy.",
    "play.settings.ogDescription": "Bàn cờ, quân cờ, âm thanh và thiết lập máy.",
    "play.settings.title": "Cài đặt",
    "play.settings.resetDefaults": "Khôi phục mặc định",
    "play.settings.board": "Bàn cờ",
    "play.settings.pieces": "Bộ quân",
    "play.settings.gameplay": "Lối chơi",
    "play.settings.showLegalMoves": "Hiện nước đi hợp lệ",
    "play.settings.showLegalMovesDesc": "Tô sáng các ô đích cho quân đang chọn.",
    "play.settings.boardCoordinates": "Toạ độ bàn cờ",
    "play.settings.boardCoordinatesDesc": "Hiện cột và hàng ở viền bàn cờ.",
    "play.settings.autoQueen": "Tự động phong Hậu",
    "play.settings.autoQueenDesc": "Luôn phong Hậu mà không hiện bảng chọn quân.",
    "play.settings.premove": "Đi trước",
    "play.settings.premoveDesc": "Đặt trước nước đi khi đối thủ đang suy nghĩ.",
    "play.settings.confirmResign": "Xác nhận chịu thua",
    "play.settings.confirmResignDesc": "Xác nhận lại trước khi chịu thua.",
    "play.settings.moveAnimations": "Hiệu ứng chuyển động",
    "play.settings.moveAnimationsDesc": "Quân cờ trượt mượt mà giữa các ô.",
    "play.settings.colorBlind": "Hỗ trợ mù màu",
    "play.settings.colorBlindDesc": "Thêm ký hiệu hình dạng để phân biệt.",
    "play.settings.sound": "Âm thanh",
    "play.settings.soundEffects": "Hiệu ứng âm thanh",
    "play.settings.soundEffectsDesc": "Âm thanh khi đi quân, bắt quân, chiếu tướng.",
    "play.settings.shatterSound": "Âm thanh vỡ kính",
    "play.settings.shatterSoundDesc": "Hiệu ứng vỡ kính khi bắt quân.",
    "play.settings.effectsVolume": "Âm lượng hiệu ứng",
    "play.settings.enginePerformance": "Hiệu năng máy",
    "play.settings.enginePerformanceDesc": "Số luồng và bộ nhớ đệm được tối ưu tự động.",
    "play.settings.performance": "Tiết kiệm",
    "play.settings.balanced": "Cân bằng",
    "play.settings.maximum": "Tối đa",
    "play.bots.level.1.title": "Người mới",
    "play.bots.level.2.title": "Nghiệp dư",
    "play.bots.level.3.title": "Phổ thông",
    "play.bots.level.4.title": "Trung cấp",
    "play.bots.level.5.title": "Câu lạc bộ",
    "play.bots.level.6.title": "Câu lạc bộ mạnh",
    "play.bots.level.7.title": "Chuyên gia",
    "play.bots.level.8.title": "Kiện tướng dự bị",
    "play.bots.level.9.title": "Kiện tướng",
    "play.bots.level.10.title": "Kiện tướng quốc tế",
    "play.bots.level.11.title": "Đại kiện tướng",
    "play.bots.level.12.title": "Siêu đại kiện tướng",
    "play.bots.level.13.title": "Máy tính",
    "play.bots.level.14.title": "Máy tính Pro",
    "play.bots.level.15.title": "Siêu máy",
    "play.bots.personality.atlas.name": "Atlas",
    "play.bots.personality.atlas.blurb": "Lối chơi thế trận. Xây dựng chậm rãi, trừng phạt sơ hở.",
    "play.bots.personality.viper.name": "Viper",
    "play.bots.personality.viper.blurb": "Thiên hướng tấn công. Truy đuổi vua đối phương ngay từ đầu.",
    "play.bots.personality.fortress.name": "Fortress",
    "play.bots.personality.fortress.blurb": "Chuyên gia phòng thủ. Đưa ván cờ về thế cờ tàn có lợi.",
    "play.bots.personality.gambit.name": "Gambit",
    "play.bots.personality.gambit.blurb": "Thí quân sớm để giành thế chủ động.",
    "play.bots.personality.nova.name": "Nova",
    "play.bots.personality.nova.blurb": "Linh hoạt và sắc bén. Ưa thích các cấu trúc mất cân bằng.",
    "play.bots.personality.oracle.name": "Oracle",
    "play.bots.personality.oracle.blurb": "Tính toán tối đa. Không phong cách, chỉ chọn nước đi tốt nhất.",
    "play.bots.personality.chaos.name": "Chaos",
    "play.bots.personality.chaos.blurb": "Chọn nước đi khó lường, nhưng vẫn rất mạnh.",
    "play.variants.standard.name": "Cổ điển",
    "play.variants.standard.blurb": "Luật cờ vua tiêu chuẩn của FIDE.",
    "play.variants.chess960.name": "Chess960",
    "play.variants.chess960.blurb": "Xáo trộn ngẫu nhiên hàng cuối với luật nhập thành Chess960.",
    "play.variants.three-check.name": "Ba lần chiếu tướng",
    "play.variants.three-check.blurb": "Thắng bằng cách chiếu vua đối phương 3 lần.",
    "play.variants.king-of-the-hill.name": "Vua trên đồi",
    "play.variants.king-of-the-hill.blurb": "Thắng bằng cách đưa vua đến các ô trung tâm.",
    "play.variants.no-queen.name": "Không Hậu",
    "play.variants.no-queen.blurb": "Luật tiêu chuẩn nhưng không có quân Hậu.",
    "play.variants.random-army.name": "Đội hình ngẫu nhiên",
    "play.variants.random-army.blurb": "Hàng cuối ngẫu nhiên nhưng đối xứng hai bên.",
}

def replace_vi(match):
    prefix = match.group(1)
    suffix = match.group(3)
    new_vi = '  vi: {\n'
    for key, value in vi_dict.items():
        new_vi += f'    "{key}": "{value}",\n'
    new_vi += '  },'
    return f'{prefix}{new_vi}{suffix}'

# Match the vi: { ... } block
pattern = re.compile(r'(export default \{\s+)(vi: \{.*?\s+\},)(.*?)(en: \{)', re.DOTALL)
new_content = pattern.sub(replace_vi, content)

with open('src/lib/i18n/dict/play.ts', 'w', encoding='utf-8') as f:
    f.write(new_content)
