import { useMemo } from "react";
import { Sparkles, TriangleAlert, Target } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useT } from "@/lib/i18n";
import { buildHighlights, type HighlightItem } from "@/lib/analysis/highlights";
import type { SavedGame } from "@/lib/history";

/**
 * Layer 1 of Game Review 3.0 — a plain-language summary built only from
 * engine facts. Every sentence is a localized template filled with numbers
 * from `buildHighlights`; nothing is generated by a language model.
 */
export function HighlightsPanel({
  game,
  onSelectMove,
}: {
  game: SavedGame;
  onSelectMove: (ply: number) => void;
}) {
  const { t } = useT();
  const color = game.playerColor ?? "w";
  const plies = game.review?.plies;

  const highlights = useMemo(
    () => (plies && plies.length > 0 ? buildHighlights(plies, color) : null),
    [plies, color],
  );

  if (!highlights) return null;

  const line = (item: HighlightItem) =>
    t(`review.highlight.${item.kind}`, item.values as Record<string, string | number>);

  return (
    <section className="panel p-4" aria-labelledby="review-highlights">
      <div className="flex items-center justify-between">
        <h2
          id="review-highlights"
          className="text-sm font-semibold uppercase tracking-wider text-muted-foreground"
        >
          {t("review.highlight.title")}
        </h2>
        <span className="tabular text-sm font-semibold">{highlights.accuracy}%</span>
      </div>

      <ul className="mt-3 space-y-2">
        {highlights.strengths.map((item) => (
          <li key={`s-${item.kind}`} className="flex gap-2 text-sm">
            <Sparkles className="mt-0.5 size-4 shrink-0 text-primary" aria-hidden />
            <span>{line(item)}</span>
          </li>
        ))}
        {highlights.improvements.map((item) => (
          <li key={`i-${item.kind}`} className="flex gap-2 text-sm">
            <TriangleAlert className="mt-0.5 size-4 shrink-0 text-muted-foreground" aria-hidden />
            <span className="flex-1">
              {line(item)}
              {item.ply !== undefined && (
                <Button
                  variant="link"
                  size="sm"
                  className="h-auto px-1 py-0"
                  onClick={() => onSelectMove(item.ply!)}
                >
                  {t("review.highlight.showOnBoard")}
                </Button>
              )}
            </span>
          </li>
        ))}
        {highlights.strengths.length === 0 && highlights.improvements.length === 0 && (
          <li className="text-sm text-muted-foreground">{t("review.highlight.empty")}</li>
        )}
      </ul>

      {highlights.biggestMiss && (
        <p className="mt-3 flex items-start gap-2 rounded-md bg-surface-2 p-3 text-sm">
          <Target className="mt-0.5 size-4 shrink-0 text-primary" aria-hidden />
          <span>
            {t("review.highlight.biggestMiss", {
              move: Math.floor(highlights.biggestMiss.ply / 2) + 1,
              san: highlights.biggestMiss.san,
              loss: highlights.biggestMiss.loss,
            })}
          </span>
        </p>
      )}
    </section>
  );
}
