/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as PlayAiRouteImport } from './routes/play.ai'
import { Route as PlayLocalRouteImport } from './routes/play.local'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayAiRoute = PlayAiRouteImport.update({
  id: '/play/ai',
  path: '/play/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLocalRoute = PlayLocalRouteImport.update({
  id: '/play/local',
  path: '/play/local',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/settings': typeof SettingsRoute
  '/play/ai': typeof PlayAiRoute
  '/play/local': typeof PlayLocalRoute
  '/games/': typeof GamesIndexRoute
  '/play/': typeof PlayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/settings': typeof SettingsRoute
  '/play/ai': typeof PlayAiRoute
  '/play/local': typeof PlayLocalRoute
  '/games': typeof GamesIndexRoute
  '/play': typeof PlayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/settings': typeof SettingsRoute
  '/play/ai': typeof PlayAiRoute
  '/play/local': typeof PlayLocalRoute
  '/games/': typeof GamesIndexRoute
  '/play/': typeof PlayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/settings'
    | '/play/ai'
    | '/play/local'
    | '/games/'
    | '/play/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/settings'
    | '/play/ai'
    | '/play/local'
    | '/games'
    | '/play'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/settings'
    | '/play/ai'
    | '/play/local'
    | '/games/'
    | '/play/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  SettingsRoute: typeof SettingsRoute
  PlayAiRoute: typeof PlayAiRoute
  PlayLocalRoute: typeof PlayLocalRoute
  GamesIndexRoute: typeof GamesIndexRoute
  PlayIndexRoute: typeof PlayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/ai': {
      id: '/play/ai'
      path: '/play/ai'
      fullPath: '/play/ai'
      preLoaderRoute: typeof PlayAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/local': {
      id: '/play/local'
      path: '/play/local'
      fullPath: '/play/local'
      preLoaderRoute: typeof PlayLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  SettingsRoute: SettingsRoute,
  PlayAiRoute: PlayAiRoute,
  PlayLocalRoute: PlayLocalRoute,
  GamesIndexRoute: GamesIndexRoute,
  PlayIndexRoute: PlayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
