/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as EndgamesRouteImport } from './routes/endgames'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as OpeningsRouteImport } from './routes/openings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedOnlineRouteImport } from './routes/_authenticated/online'
import { Route as AuthenticatedSkillsRouteImport } from './routes/_authenticated/skills'
import { Route as AuthenticatedTrainingPlanRouteImport } from './routes/_authenticated/training-plan'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as DrillsIndexRouteImport } from './routes/drills.index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as PlayAiRouteImport } from './routes/play.ai'
import { Route as PlayCoachRouteImport } from './routes/play.coach'
import { Route as PlayLocalRouteImport } from './routes/play.local'
import { Route as PlayShareRouteImport } from './routes/play.share'
import { Route as PlayVariantsRouteImport } from './routes/play.variants'
import { Route as PuzzlesIndexRouteImport } from './routes/puzzles.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminEngineRouteImport } from './routes/_authenticated/admin.engine'
import { Route as AuthenticatedAdminIntelligenceRouteImport } from './routes/_authenticated/admin.intelligence'
import { Route as AuthenticatedAdminLearnRouteImport } from './routes/_authenticated/admin.learn'
import { Route as AuthenticatedAdminOpeningsRouteImport } from './routes/_authenticated/admin.openings'
import { Route as AuthenticatedAdminPuzzlesRouteImport } from './routes/_authenticated/admin.puzzles'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin.security'
import { Route as AuthenticatedAdminSystemRouteImport } from './routes/_authenticated/admin.system'
import { Route as AuthenticatedAdminTournamentsRouteImport } from './routes/_authenticated/admin.tournaments'
import { Route as AuthenticatedGameGameIdRouteImport } from './routes/_authenticated/game.$gameId'
import { Route as AuthenticatedOnlineDiagnosticsRouteImport } from './routes/_authenticated/online.diagnostics'
import { Route as AuthenticatedPuzzlesTrainRouteImport } from './routes/_authenticated/puzzles.train'
import { Route as AuthenticatedTournamentsIndexRouteImport } from './routes/_authenticated/tournaments.index'
import { Route as AuthenticatedTournamentsSlugRouteImport } from './routes/_authenticated/tournaments.$slug'
import { Route as AuthenticatedWatchIndexRouteImport } from './routes/_authenticated/watch.index'
import { Route as AuthenticatedWatchGameIdRouteImport } from './routes/_authenticated/watch.$gameId'
import { Route as GamesOnlineGameIdRouteImport } from './routes/games.online.$gameId'
import { Route as LearnCourseSlugRouteImport } from './routes/learn.course.$slug'
import { Route as LearnLessonSlugRouteImport } from './routes/learn.lesson.$slug'
import { Route as AuthenticatedAdminFairplayIndexRouteImport } from './routes/_authenticated/admin.fairplay.index'
import { Route as AuthenticatedAdminFairplayLogRouteImport } from './routes/_authenticated/admin.fairplay.log'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin.users.index'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin.users.$userId'
import { Route as ApiPublicFairplayClaimRouteImport } from './routes/api/public/fairplay/claim'
import { Route as ApiPublicFairplayFailRouteImport } from './routes/api/public/fairplay/fail'
import { Route as ApiPublicFairplayResultRouteImport } from './routes/api/public/fairplay/result'
import { Route as ApiPublicTournamentsTickRouteImport } from './routes/api/public/tournaments/tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EndgamesRoute = EndgamesRouteImport.update({
  id: '/endgames',
  path: '/endgames',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningsRoute = OpeningsRouteImport.update({
  id: '/openings',
  path: '/openings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnlineRoute = AuthenticatedOnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillsRoute = AuthenticatedSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrainingPlanRoute =
  AuthenticatedTrainingPlanRouteImport.update({
    id: '/training-plan',
    path: '/training-plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillsIndexRoute = DrillsIndexRouteImport.update({
  id: '/drills/',
  path: '/drills/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayAiRoute = PlayAiRouteImport.update({
  id: '/play/ai',
  path: '/play/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCoachRoute = PlayCoachRouteImport.update({
  id: '/play/coach',
  path: '/play/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLocalRoute = PlayLocalRouteImport.update({
  id: '/play/local',
  path: '/play/local',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayShareRoute = PlayShareRouteImport.update({
  id: '/play/share',
  path: '/play/share',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayVariantsRoute = PlayVariantsRouteImport.update({
  id: '/play/variants',
  path: '/play/variants',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesIndexRoute = PuzzlesIndexRouteImport.update({
  id: '/puzzles/',
  path: '/puzzles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminEngineRoute =
  AuthenticatedAdminEngineRouteImport.update({
    id: '/admin/engine',
    path: '/admin/engine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIntelligenceRoute =
  AuthenticatedAdminIntelligenceRouteImport.update({
    id: '/admin/intelligence',
    path: '/admin/intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLearnRoute = AuthenticatedAdminLearnRouteImport.update({
  id: '/admin/learn',
  path: '/admin/learn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminOpeningsRoute =
  AuthenticatedAdminOpeningsRouteImport.update({
    id: '/admin/openings',
    path: '/admin/openings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPuzzlesRoute =
  AuthenticatedAdminPuzzlesRouteImport.update({
    id: '/admin/puzzles',
    path: '/admin/puzzles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/admin/security',
    path: '/admin/security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSystemRoute =
  AuthenticatedAdminSystemRouteImport.update({
    id: '/admin/system',
    path: '/admin/system',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTournamentsRoute =
  AuthenticatedAdminTournamentsRouteImport.update({
    id: '/admin/tournaments',
    path: '/admin/tournaments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGameGameIdRoute = AuthenticatedGameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnlineDiagnosticsRoute =
  AuthenticatedOnlineDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedOnlineRoute,
  } as any)
const AuthenticatedPuzzlesTrainRoute =
  AuthenticatedPuzzlesTrainRouteImport.update({
    id: '/puzzles/train',
    path: '/puzzles/train',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTournamentsIndexRoute =
  AuthenticatedTournamentsIndexRouteImport.update({
    id: '/tournaments/',
    path: '/tournaments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTournamentsSlugRoute =
  AuthenticatedTournamentsSlugRouteImport.update({
    id: '/tournaments/$slug',
    path: '/tournaments/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWatchIndexRoute = AuthenticatedWatchIndexRouteImport.update({
  id: '/watch/',
  path: '/watch/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWatchGameIdRoute =
  AuthenticatedWatchGameIdRouteImport.update({
    id: '/watch/$gameId',
    path: '/watch/$gameId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const GamesOnlineGameIdRoute = GamesOnlineGameIdRouteImport.update({
  id: '/games/online/$gameId',
  path: '/games/online/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseSlugRoute = LearnCourseSlugRouteImport.update({
  id: '/learn/course/$slug',
  path: '/learn/course/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonSlugRoute = LearnLessonSlugRouteImport.update({
  id: '/learn/lesson/$slug',
  path: '/learn/lesson/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminFairplayIndexRoute =
  AuthenticatedAdminFairplayIndexRouteImport.update({
    id: '/admin/fairplay/',
    path: '/admin/fairplay/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFairplayLogRoute =
  AuthenticatedAdminFairplayLogRouteImport.update({
    id: '/admin/fairplay/log',
    path: '/admin/fairplay/log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/admin/users/$userId',
    path: '/admin/users/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicFairplayClaimRoute = ApiPublicFairplayClaimRouteImport.update({
  id: '/api/public/fairplay/claim',
  path: '/api/public/fairplay/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFairplayFailRoute = ApiPublicFairplayFailRouteImport.update({
  id: '/api/public/fairplay/fail',
  path: '/api/public/fairplay/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFairplayResultRoute = ApiPublicFairplayResultRouteImport.update({
  id: '/api/public/fairplay/result',
  path: '/api/public/fairplay/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTournamentsTickRoute =
  ApiPublicTournamentsTickRouteImport.update({
    id: '/api/public/tournaments/tick',
    path: '/api/public/tournaments/tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/endgames': typeof EndgamesRoute
  '/insights': typeof InsightsRoute
  '/openings': typeof OpeningsRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/online': typeof AuthenticatedOnlineRouteWithChildren
  '/skills': typeof AuthenticatedSkillsRoute
  '/training-plan': typeof AuthenticatedTrainingPlanRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/play/ai': typeof PlayAiRoute
  '/play/coach': typeof PlayCoachRoute
  '/play/local': typeof PlayLocalRoute
  '/play/share': typeof PlayShareRoute
  '/play/variants': typeof PlayVariantsRoute
  '/drills/': typeof DrillsIndexRoute
  '/games/': typeof GamesIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/play/': typeof PlayIndexRoute
  '/puzzles/': typeof PuzzlesIndexRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/engine': typeof AuthenticatedAdminEngineRoute
  '/admin/intelligence': typeof AuthenticatedAdminIntelligenceRoute
  '/admin/learn': typeof AuthenticatedAdminLearnRoute
  '/admin/openings': typeof AuthenticatedAdminOpeningsRoute
  '/admin/puzzles': typeof AuthenticatedAdminPuzzlesRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/system': typeof AuthenticatedAdminSystemRoute
  '/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/game/$gameId': typeof AuthenticatedGameGameIdRoute
  '/online/diagnostics': typeof AuthenticatedOnlineDiagnosticsRoute
  '/puzzles/train': typeof AuthenticatedPuzzlesTrainRoute
  '/tournaments/$slug': typeof AuthenticatedTournamentsSlugRoute
  '/watch/$gameId': typeof AuthenticatedWatchGameIdRoute
  '/games/online/$gameId': typeof GamesOnlineGameIdRoute
  '/learn/course/$slug': typeof LearnCourseSlugRoute
  '/learn/lesson/$slug': typeof LearnLessonSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/tournaments/': typeof AuthenticatedTournamentsIndexRoute
  '/watch/': typeof AuthenticatedWatchIndexRoute
  '/admin/fairplay/log': typeof AuthenticatedAdminFairplayLogRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/fairplay/claim': typeof ApiPublicFairplayClaimRoute
  '/api/public/fairplay/fail': typeof ApiPublicFairplayFailRoute
  '/api/public/fairplay/result': typeof ApiPublicFairplayResultRoute
  '/api/public/tournaments/tick': typeof ApiPublicTournamentsTickRoute
  '/admin/fairplay/': typeof AuthenticatedAdminFairplayIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/endgames': typeof EndgamesRoute
  '/insights': typeof InsightsRoute
  '/openings': typeof OpeningsRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/online': typeof AuthenticatedOnlineRouteWithChildren
  '/skills': typeof AuthenticatedSkillsRoute
  '/training-plan': typeof AuthenticatedTrainingPlanRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/play/ai': typeof PlayAiRoute
  '/play/coach': typeof PlayCoachRoute
  '/play/local': typeof PlayLocalRoute
  '/play/share': typeof PlayShareRoute
  '/play/variants': typeof PlayVariantsRoute
  '/drills': typeof DrillsIndexRoute
  '/games': typeof GamesIndexRoute
  '/learn': typeof LearnIndexRoute
  '/play': typeof PlayIndexRoute
  '/puzzles': typeof PuzzlesIndexRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/engine': typeof AuthenticatedAdminEngineRoute
  '/admin/intelligence': typeof AuthenticatedAdminIntelligenceRoute
  '/admin/learn': typeof AuthenticatedAdminLearnRoute
  '/admin/openings': typeof AuthenticatedAdminOpeningsRoute
  '/admin/puzzles': typeof AuthenticatedAdminPuzzlesRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/system': typeof AuthenticatedAdminSystemRoute
  '/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/game/$gameId': typeof AuthenticatedGameGameIdRoute
  '/online/diagnostics': typeof AuthenticatedOnlineDiagnosticsRoute
  '/puzzles/train': typeof AuthenticatedPuzzlesTrainRoute
  '/tournaments/$slug': typeof AuthenticatedTournamentsSlugRoute
  '/watch/$gameId': typeof AuthenticatedWatchGameIdRoute
  '/games/online/$gameId': typeof GamesOnlineGameIdRoute
  '/learn/course/$slug': typeof LearnCourseSlugRoute
  '/learn/lesson/$slug': typeof LearnLessonSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/tournaments': typeof AuthenticatedTournamentsIndexRoute
  '/watch': typeof AuthenticatedWatchIndexRoute
  '/admin/fairplay/log': typeof AuthenticatedAdminFairplayLogRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/fairplay/claim': typeof ApiPublicFairplayClaimRoute
  '/api/public/fairplay/fail': typeof ApiPublicFairplayFailRoute
  '/api/public/fairplay/result': typeof ApiPublicFairplayResultRoute
  '/api/public/tournaments/tick': typeof ApiPublicTournamentsTickRoute
  '/admin/fairplay': typeof AuthenticatedAdminFairplayIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/analysis': typeof AnalysisRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/endgames': typeof EndgamesRoute
  '/insights': typeof InsightsRoute
  '/openings': typeof OpeningsRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/online': typeof AuthenticatedOnlineRouteWithChildren
  '/_authenticated/skills': typeof AuthenticatedSkillsRoute
  '/_authenticated/training-plan': typeof AuthenticatedTrainingPlanRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/play/ai': typeof PlayAiRoute
  '/play/coach': typeof PlayCoachRoute
  '/play/local': typeof PlayLocalRoute
  '/play/share': typeof PlayShareRoute
  '/play/variants': typeof PlayVariantsRoute
  '/drills/': typeof DrillsIndexRoute
  '/games/': typeof GamesIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/play/': typeof PlayIndexRoute
  '/puzzles/': typeof PuzzlesIndexRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/engine': typeof AuthenticatedAdminEngineRoute
  '/_authenticated/admin/intelligence': typeof AuthenticatedAdminIntelligenceRoute
  '/_authenticated/admin/learn': typeof AuthenticatedAdminLearnRoute
  '/_authenticated/admin/openings': typeof AuthenticatedAdminOpeningsRoute
  '/_authenticated/admin/puzzles': typeof AuthenticatedAdminPuzzlesRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/system': typeof AuthenticatedAdminSystemRoute
  '/_authenticated/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/_authenticated/game/$gameId': typeof AuthenticatedGameGameIdRoute
  '/_authenticated/online/diagnostics': typeof AuthenticatedOnlineDiagnosticsRoute
  '/_authenticated/puzzles/train': typeof AuthenticatedPuzzlesTrainRoute
  '/_authenticated/tournaments/$slug': typeof AuthenticatedTournamentsSlugRoute
  '/_authenticated/watch/$gameId': typeof AuthenticatedWatchGameIdRoute
  '/games/online/$gameId': typeof GamesOnlineGameIdRoute
  '/learn/course/$slug': typeof LearnCourseSlugRoute
  '/learn/lesson/$slug': typeof LearnLessonSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/tournaments/': typeof AuthenticatedTournamentsIndexRoute
  '/_authenticated/watch/': typeof AuthenticatedWatchIndexRoute
  '/_authenticated/admin/fairplay/log': typeof AuthenticatedAdminFairplayLogRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/fairplay/claim': typeof ApiPublicFairplayClaimRoute
  '/api/public/fairplay/fail': typeof ApiPublicFairplayFailRoute
  '/api/public/fairplay/result': typeof ApiPublicFairplayResultRoute
  '/api/public/tournaments/tick': typeof ApiPublicTournamentsTickRoute
  '/_authenticated/admin/fairplay/': typeof AuthenticatedAdminFairplayIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/contact'
    | '/cookie-policy'
    | '/endgames'
    | '/insights'
    | '/openings'
    | '/privacy'
    | '/progress'
    | '/settings'
    | '/terms'
    | '/account'
    | '/online'
    | '/skills'
    | '/training-plan'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/games/$gameId'
    | '/play/ai'
    | '/play/coach'
    | '/play/local'
    | '/play/share'
    | '/play/variants'
    | '/drills/'
    | '/games/'
    | '/learn/'
    | '/play/'
    | '/puzzles/'
    | '/admin/audit'
    | '/admin/engine'
    | '/admin/intelligence'
    | '/admin/learn'
    | '/admin/openings'
    | '/admin/puzzles'
    | '/admin/security'
    | '/admin/system'
    | '/admin/tournaments'
    | '/game/$gameId'
    | '/online/diagnostics'
    | '/puzzles/train'
    | '/tournaments/$slug'
    | '/watch/$gameId'
    | '/games/online/$gameId'
    | '/learn/course/$slug'
    | '/learn/lesson/$slug'
    | '/admin/'
    | '/tournaments/'
    | '/watch/'
    | '/admin/fairplay/log'
    | '/admin/users/$userId'
    | '/api/public/fairplay/claim'
    | '/api/public/fairplay/fail'
    | '/api/public/fairplay/result'
    | '/api/public/tournaments/tick'
    | '/admin/fairplay/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/contact'
    | '/cookie-policy'
    | '/endgames'
    | '/insights'
    | '/openings'
    | '/privacy'
    | '/progress'
    | '/settings'
    | '/terms'
    | '/account'
    | '/online'
    | '/skills'
    | '/training-plan'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/games/$gameId'
    | '/play/ai'
    | '/play/coach'
    | '/play/local'
    | '/play/share'
    | '/play/variants'
    | '/drills'
    | '/games'
    | '/learn'
    | '/play'
    | '/puzzles'
    | '/admin/audit'
    | '/admin/engine'
    | '/admin/intelligence'
    | '/admin/learn'
    | '/admin/openings'
    | '/admin/puzzles'
    | '/admin/security'
    | '/admin/system'
    | '/admin/tournaments'
    | '/game/$gameId'
    | '/online/diagnostics'
    | '/puzzles/train'
    | '/tournaments/$slug'
    | '/watch/$gameId'
    | '/games/online/$gameId'
    | '/learn/course/$slug'
    | '/learn/lesson/$slug'
    | '/admin'
    | '/tournaments'
    | '/watch'
    | '/admin/fairplay/log'
    | '/admin/users/$userId'
    | '/api/public/fairplay/claim'
    | '/api/public/fairplay/fail'
    | '/api/public/fairplay/result'
    | '/api/public/tournaments/tick'
    | '/admin/fairplay'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/analysis'
    | '/contact'
    | '/cookie-policy'
    | '/endgames'
    | '/insights'
    | '/openings'
    | '/privacy'
    | '/progress'
    | '/settings'
    | '/terms'
    | '/_authenticated/account'
    | '/_authenticated/online'
    | '/_authenticated/skills'
    | '/_authenticated/training-plan'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/games/$gameId'
    | '/play/ai'
    | '/play/coach'
    | '/play/local'
    | '/play/share'
    | '/play/variants'
    | '/drills/'
    | '/games/'
    | '/learn/'
    | '/play/'
    | '/puzzles/'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/engine'
    | '/_authenticated/admin/intelligence'
    | '/_authenticated/admin/learn'
    | '/_authenticated/admin/openings'
    | '/_authenticated/admin/puzzles'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/system'
    | '/_authenticated/admin/tournaments'
    | '/_authenticated/game/$gameId'
    | '/_authenticated/online/diagnostics'
    | '/_authenticated/puzzles/train'
    | '/_authenticated/tournaments/$slug'
    | '/_authenticated/watch/$gameId'
    | '/games/online/$gameId'
    | '/learn/course/$slug'
    | '/learn/lesson/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/tournaments/'
    | '/_authenticated/watch/'
    | '/_authenticated/admin/fairplay/log'
    | '/_authenticated/admin/users/$userId'
    | '/api/public/fairplay/claim'
    | '/api/public/fairplay/fail'
    | '/api/public/fairplay/result'
    | '/api/public/tournaments/tick'
    | '/_authenticated/admin/fairplay/'
    | '/_authenticated/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnalysisRoute: typeof AnalysisRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  EndgamesRoute: typeof EndgamesRoute
  InsightsRoute: typeof InsightsRoute
  OpeningsRoute: typeof OpeningsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  PlayAiRoute: typeof PlayAiRoute
  PlayCoachRoute: typeof PlayCoachRoute
  PlayLocalRoute: typeof PlayLocalRoute
  PlayShareRoute: typeof PlayShareRoute
  PlayVariantsRoute: typeof PlayVariantsRoute
  DrillsIndexRoute: typeof DrillsIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  PlayIndexRoute: typeof PlayIndexRoute
  PuzzlesIndexRoute: typeof PuzzlesIndexRoute
  GamesOnlineGameIdRoute: typeof GamesOnlineGameIdRoute
  LearnCourseSlugRoute: typeof LearnCourseSlugRoute
  LearnLessonSlugRoute: typeof LearnLessonSlugRoute
  ApiPublicFairplayClaimRoute: typeof ApiPublicFairplayClaimRoute
  ApiPublicFairplayFailRoute: typeof ApiPublicFairplayFailRoute
  ApiPublicFairplayResultRoute: typeof ApiPublicFairplayResultRoute
  ApiPublicTournamentsTickRoute: typeof ApiPublicTournamentsTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endgames': {
      id: '/endgames'
      path: '/endgames'
      fullPath: '/endgames'
      preLoaderRoute: typeof EndgamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openings': {
      id: '/openings'
      path: '/openings'
      fullPath: '/openings'
      preLoaderRoute: typeof OpeningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/online': {
      id: '/_authenticated/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof AuthenticatedOnlineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills': {
      id: '/_authenticated/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training-plan': {
      id: '/_authenticated/training-plan'
      path: '/training-plan'
      fullPath: '/training-plan'
      preLoaderRoute: typeof AuthenticatedTrainingPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drills/': {
      id: '/drills/'
      path: '/drills'
      fullPath: '/drills/'
      preLoaderRoute: typeof DrillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/ai': {
      id: '/play/ai'
      path: '/play/ai'
      fullPath: '/play/ai'
      preLoaderRoute: typeof PlayAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/coach': {
      id: '/play/coach'
      path: '/play/coach'
      fullPath: '/play/coach'
      preLoaderRoute: typeof PlayCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/local': {
      id: '/play/local'
      path: '/play/local'
      fullPath: '/play/local'
      preLoaderRoute: typeof PlayLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/share': {
      id: '/play/share'
      path: '/play/share'
      fullPath: '/play/share'
      preLoaderRoute: typeof PlayShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/variants': {
      id: '/play/variants'
      path: '/play/variants'
      fullPath: '/play/variants'
      preLoaderRoute: typeof PlayVariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/': {
      id: '/puzzles/'
      path: '/puzzles'
      fullPath: '/puzzles/'
      preLoaderRoute: typeof PuzzlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/engine': {
      id: '/_authenticated/admin/engine'
      path: '/admin/engine'
      fullPath: '/admin/engine'
      preLoaderRoute: typeof AuthenticatedAdminEngineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/intelligence': {
      id: '/_authenticated/admin/intelligence'
      path: '/admin/intelligence'
      fullPath: '/admin/intelligence'
      preLoaderRoute: typeof AuthenticatedAdminIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/learn': {
      id: '/_authenticated/admin/learn'
      path: '/admin/learn'
      fullPath: '/admin/learn'
      preLoaderRoute: typeof AuthenticatedAdminLearnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/openings': {
      id: '/_authenticated/admin/openings'
      path: '/admin/openings'
      fullPath: '/admin/openings'
      preLoaderRoute: typeof AuthenticatedAdminOpeningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/puzzles': {
      id: '/_authenticated/admin/puzzles'
      path: '/admin/puzzles'
      fullPath: '/admin/puzzles'
      preLoaderRoute: typeof AuthenticatedAdminPuzzlesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/system': {
      id: '/_authenticated/admin/system'
      path: '/admin/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AuthenticatedAdminSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tournaments': {
      id: '/_authenticated/admin/tournaments'
      path: '/admin/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AuthenticatedAdminTournamentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/game/$gameId': {
      id: '/_authenticated/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof AuthenticatedGameGameIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/online/diagnostics': {
      id: '/_authenticated/online/diagnostics'
      path: '/diagnostics'
      fullPath: '/online/diagnostics'
      preLoaderRoute: typeof AuthenticatedOnlineDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedOnlineRoute
    }
    '/_authenticated/puzzles/train': {
      id: '/_authenticated/puzzles/train'
      path: '/puzzles/train'
      fullPath: '/puzzles/train'
      preLoaderRoute: typeof AuthenticatedPuzzlesTrainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tournaments/': {
      id: '/_authenticated/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof AuthenticatedTournamentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tournaments/$slug': {
      id: '/_authenticated/tournaments/$slug'
      path: '/tournaments/$slug'
      fullPath: '/tournaments/$slug'
      preLoaderRoute: typeof AuthenticatedTournamentsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watch/': {
      id: '/_authenticated/watch/'
      path: '/watch'
      fullPath: '/watch/'
      preLoaderRoute: typeof AuthenticatedWatchIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watch/$gameId': {
      id: '/_authenticated/watch/$gameId'
      path: '/watch/$gameId'
      fullPath: '/watch/$gameId'
      preLoaderRoute: typeof AuthenticatedWatchGameIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/games/online/$gameId': {
      id: '/games/online/$gameId'
      path: '/games/online/$gameId'
      fullPath: '/games/online/$gameId'
      preLoaderRoute: typeof GamesOnlineGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/course/$slug': {
      id: '/learn/course/$slug'
      path: '/learn/course/$slug'
      fullPath: '/learn/course/$slug'
      preLoaderRoute: typeof LearnCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/lesson/$slug': {
      id: '/learn/lesson/$slug'
      path: '/learn/lesson/$slug'
      fullPath: '/learn/lesson/$slug'
      preLoaderRoute: typeof LearnLessonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/fairplay/': {
      id: '/_authenticated/admin/fairplay/'
      path: '/admin/fairplay'
      fullPath: '/admin/fairplay/'
      preLoaderRoute: typeof AuthenticatedAdminFairplayIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/fairplay/log': {
      id: '/_authenticated/admin/fairplay/log'
      path: '/admin/fairplay/log'
      fullPath: '/admin/fairplay/log'
      preLoaderRoute: typeof AuthenticatedAdminFairplayLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/fairplay/claim': {
      id: '/api/public/fairplay/claim'
      path: '/api/public/fairplay/claim'
      fullPath: '/api/public/fairplay/claim'
      preLoaderRoute: typeof ApiPublicFairplayClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fairplay/fail': {
      id: '/api/public/fairplay/fail'
      path: '/api/public/fairplay/fail'
      fullPath: '/api/public/fairplay/fail'
      preLoaderRoute: typeof ApiPublicFairplayFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fairplay/result': {
      id: '/api/public/fairplay/result'
      path: '/api/public/fairplay/result'
      fullPath: '/api/public/fairplay/result'
      preLoaderRoute: typeof ApiPublicFairplayResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tournaments/tick': {
      id: '/api/public/tournaments/tick'
      path: '/api/public/tournaments/tick'
      fullPath: '/api/public/tournaments/tick'
      preLoaderRoute: typeof ApiPublicTournamentsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedOnlineRouteChildren {
  AuthenticatedOnlineDiagnosticsRoute: typeof AuthenticatedOnlineDiagnosticsRoute
}

const AuthenticatedOnlineRouteChildren: AuthenticatedOnlineRouteChildren = {
  AuthenticatedOnlineDiagnosticsRoute: AuthenticatedOnlineDiagnosticsRoute,
}

const AuthenticatedOnlineRouteWithChildren =
  AuthenticatedOnlineRoute._addFileChildren(AuthenticatedOnlineRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedOnlineRoute: typeof AuthenticatedOnlineRouteWithChildren
  AuthenticatedSkillsRoute: typeof AuthenticatedSkillsRoute
  AuthenticatedTrainingPlanRoute: typeof AuthenticatedTrainingPlanRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminEngineRoute: typeof AuthenticatedAdminEngineRoute
  AuthenticatedAdminIntelligenceRoute: typeof AuthenticatedAdminIntelligenceRoute
  AuthenticatedAdminLearnRoute: typeof AuthenticatedAdminLearnRoute
  AuthenticatedAdminOpeningsRoute: typeof AuthenticatedAdminOpeningsRoute
  AuthenticatedAdminPuzzlesRoute: typeof AuthenticatedAdminPuzzlesRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminSystemRoute: typeof AuthenticatedAdminSystemRoute
  AuthenticatedAdminTournamentsRoute: typeof AuthenticatedAdminTournamentsRoute
  AuthenticatedGameGameIdRoute: typeof AuthenticatedGameGameIdRoute
  AuthenticatedPuzzlesTrainRoute: typeof AuthenticatedPuzzlesTrainRoute
  AuthenticatedTournamentsSlugRoute: typeof AuthenticatedTournamentsSlugRoute
  AuthenticatedWatchGameIdRoute: typeof AuthenticatedWatchGameIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedTournamentsIndexRoute: typeof AuthenticatedTournamentsIndexRoute
  AuthenticatedWatchIndexRoute: typeof AuthenticatedWatchIndexRoute
  AuthenticatedAdminFairplayLogRoute: typeof AuthenticatedAdminFairplayLogRoute
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
  AuthenticatedAdminFairplayIndexRoute: typeof AuthenticatedAdminFairplayIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedOnlineRoute: AuthenticatedOnlineRouteWithChildren,
  AuthenticatedSkillsRoute: AuthenticatedSkillsRoute,
  AuthenticatedTrainingPlanRoute: AuthenticatedTrainingPlanRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminEngineRoute: AuthenticatedAdminEngineRoute,
  AuthenticatedAdminIntelligenceRoute: AuthenticatedAdminIntelligenceRoute,
  AuthenticatedAdminLearnRoute: AuthenticatedAdminLearnRoute,
  AuthenticatedAdminOpeningsRoute: AuthenticatedAdminOpeningsRoute,
  AuthenticatedAdminPuzzlesRoute: AuthenticatedAdminPuzzlesRoute,
  AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
  AuthenticatedAdminSystemRoute: AuthenticatedAdminSystemRoute,
  AuthenticatedAdminTournamentsRoute: AuthenticatedAdminTournamentsRoute,
  AuthenticatedGameGameIdRoute: AuthenticatedGameGameIdRoute,
  AuthenticatedPuzzlesTrainRoute: AuthenticatedPuzzlesTrainRoute,
  AuthenticatedTournamentsSlugRoute: AuthenticatedTournamentsSlugRoute,
  AuthenticatedWatchGameIdRoute: AuthenticatedWatchGameIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedTournamentsIndexRoute: AuthenticatedTournamentsIndexRoute,
  AuthenticatedWatchIndexRoute: AuthenticatedWatchIndexRoute,
  AuthenticatedAdminFairplayLogRoute: AuthenticatedAdminFairplayLogRoute,
  AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
  AuthenticatedAdminFairplayIndexRoute: AuthenticatedAdminFairplayIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnalysisRoute: AnalysisRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  EndgamesRoute: EndgamesRoute,
  InsightsRoute: InsightsRoute,
  OpeningsRoute: OpeningsRoute,
  PrivacyRoute: PrivacyRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  PlayAiRoute: PlayAiRoute,
  PlayCoachRoute: PlayCoachRoute,
  PlayLocalRoute: PlayLocalRoute,
  PlayShareRoute: PlayShareRoute,
  PlayVariantsRoute: PlayVariantsRoute,
  DrillsIndexRoute: DrillsIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  PlayIndexRoute: PlayIndexRoute,
  PuzzlesIndexRoute: PuzzlesIndexRoute,
  GamesOnlineGameIdRoute: GamesOnlineGameIdRoute,
  LearnCourseSlugRoute: LearnCourseSlugRoute,
  LearnLessonSlugRoute: LearnLessonSlugRoute,
  ApiPublicFairplayClaimRoute: ApiPublicFairplayClaimRoute,
  ApiPublicFairplayFailRoute: ApiPublicFairplayFailRoute,
  ApiPublicFairplayResultRoute: ApiPublicFairplayResultRoute,
  ApiPublicTournamentsTickRoute: ApiPublicTournamentsTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
